name: teardown
synopsis: Build composable, idempotent & transparent application cleanup sub-routines
description: Please see README.md
version: '0.0.0.3'
category: System
author: Roman Gonzalez
maintainer: romanandreg@gmail.com
copyright: © 2017 Roman Gonzalez
license: MIT
github: roman/Haskell-teardown
tested-with: GHC==7.10.3 GHC==8.0.1 GHC==8.0.2
extra-source-files:
- README.md
- CHANGELOG.md
ghc-options:
- -Wall
dependencies:
- base >=4.8 && <5
- protolude >=0.1 && <0.2
- text >=1.2 && <1.3
- time >=1.5 && <1.7
library:
  source-dirs: src
  exposed-modules:
  - Control.Teardown
  other-modules:
  - Control.Teardown.Internal.Core
  - Control.Teardown.Internal.Printer
  dependencies:
  - ansi-wl-pprint >=0.6 && <0.7
tests:
  teardown-test:
    main: TestSuite.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tasty >=0.11 && <0.12
    - tasty-hunit >=0.9 && <0.10
    - tasty-hspec >=1.1 && <1.2
    - tasty-smallcheck >=0.8 && <0.9
    - tasty-rerun >=1.1 && <1.2
    - teardown
  teardown-doctest:
    main: DocTest.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - doctest >=0.11 && <0.12
    - Glob >=0.7 && <0.9
    - QuickCheck >=2.8 && <2.10
    - teardown
benchmarks:
  teardown-benchmark:
    main: Main.hs
    source-dirs: benchmark
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - criterion >=1.1 && <1.2
    - teardown
stability: alpha (experimental)
