name: teardown
synopsis: Build composable, idempotent & transparent application cleanup sub-routines
description: Please see README.md
version: '0.3.0.0'
category: System
author: Roman Gonzalez
maintainer: romanandreg@gmail.com
copyright: © 2017 Roman Gonzalez
license: MIT
github: roman/Haskell-teardown
tested-with: GHC==7.10.3 GHC==8.0.1 GHC==8.0.2
extra-source-files:
- README.md
- CHANGELOG.md
ghc-options:
- -Wall
dependencies:
- base >=4.8 && <5
- protolude
- safe-exceptions
- text
- time
library:
  source-dirs: src
  exposed-modules:
  - Control.Teardown
  - Control.Monad.Component
  other-modules:
  - Control.Teardown.Internal.Types
  - Control.Teardown.Internal.Core
  - Control.Teardown.Internal.Printer
  - Control.Monad.Component.Internal.Types
  - Control.Monad.Component.Internal.Core
  dependencies:
  - ansi-wl-pprint
  - exceptions
  - deepseq
tests:
  teardown-test:
    main: TestSuite.hs
    source-dirs: test/tasty
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tasty
    - tasty-hunit
    - tasty-hspec
    - tasty-smallcheck
    - tasty-rerun
    - teardown
  teardown-doctest:
    main: DocTest.hs
    source-dirs: test/doctest
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - doctest
    - Glob
    - QuickCheck
    - teardown
benchmarks:
  teardown-benchmark:
    main: Main.hs
    source-dirs: benchmark
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - criterion >=1.1 && <1.3
    - teardown
stability: alpha (experimental)
