name: teardown
version: '0.3.0.0'
synopsis: Build composable components for your application with clear teardown semantics
description: |
  The teardown library allows you to reliably execute cleanup sub-routines for
  allocated resources when a program is initialized; it:

  * Ensures that teardown sub-routines are executed /exactly/ once, even on the
    scenario where cleanup is invoked multiple times

  * Ensures that if errors occur on the execution of one teardown, the error
    doesn not propagate to other sub-routines; effectively keeping them
    isolated.

  * Requires every teardown sub-routine to be documented at creation time; thus
    helping tracing your application structure.

  * Allows tracing the teardown of your application, how is structured, how much
    time it takes to execute, what component failed to finalize, and if the
    whole teardown was successful.

category: System
author: Roman Gonzalez
maintainer: open-source@roman-gonzalez.info
copyright: © 2017, 2018 Roman Gonzalez
license: MIT
github: roman/Haskell-teardown
tested-with: GHC==8.0.1 GHC==8.0.2 GHC==8.2.1
extra-source-files:
- README.md
- CHANGELOG.md
ghc-options:
- -Wall
# as recommended in:
# https://functor.tokyo/blog/2017-07-28-ghc-warnings-you-should-enable
- -Wincomplete-uni-patterns
- -Wincomplete-record-updates
dependencies:
- base >=4.8 && <5
- rio >= 0.0.1.0
library:
  source-dirs: src
  exposed-modules:
  - Control.Teardown
  - Control.Teardown.Tutorial
  - Control.Monad.Component
  other-modules:
  - Control.Teardown.Internal.Types
  - Control.Teardown.Internal.Core
  - Control.Teardown.Internal.Printer
  - Control.Monad.Component.Internal.Types
  - Control.Monad.Component.Internal.Core
  dependencies:
  - ansi-wl-pprint
tests:
  teardown-test:
    main: TestSuite.hs
    source-dirs: test/tasty
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tasty
    - tasty-hunit
    - tasty-hspec
    - tasty-smallcheck
    - tasty-rerun
    - teardown
  teardown-doctest:
    main: DocTest.hs
    source-dirs: test/doctest
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - doctest
    - Glob
    - QuickCheck
    - teardown
benchmarks:
  teardown-benchmark:
    main: Main.hs
    source-dirs: benchmark
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - criterion >=1.1 && <1.3
    - teardown
stability: alpha (experimental)
