name: teardown
version: '0.0.0.1'
category: Test
author: TODO:<Author name here>
maintainer: TODO:<example@example.com>
copyright: © 2017 TODO:<Author name here>
license: MIT
github: roman/Haskell-teardown
tested-with: GHC==7.10.3 GHC==8.0.1 GHC==8.0.2
extra-source-files:
- README.md
- CHANGELOG.md
- stack.yaml
ghc-options:
- -Wall
- -Werror
- -O2
dependencies:
- base >=4.8 && <5
- protolude
- text
- time
library:
  source-dirs: src
  exposed-modules:
  - Control.Teardown
  other-modules:
  - Control.Teardown.Internal.Core
  - Control.Teardown.Internal.Printer
  dependencies:
  - ansi-wl-pprint
tests:
  teardown-test:
    main: TestSuite.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tasty
    - tasty-hunit
    - tasty-hspec
    - tasty-smallcheck
    - tasty-rerun
    - teardown
  teardown-doctest:
    main: DocTest.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - doctest
    - Glob
    - QuickCheck
    - teardown
benchmarks:
  teardown-benchmark:
    main: Main.hs
    source-dirs: benchmark
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - criterion
    - teardown
stability: alpha (experimental)
