flags:
  generic-deriving:
    base-4-9: false
extra-package-dbs: []
packages:
- .
- examples/teardown-example
extra-deps:
- Glob-0.9.2
- aeson-1.2.4.0
- base-orphans-0.7
- bifunctors-5.5.2
- comonad-5.0.3
- criterion-1.4.0.0
- exceptions-0.10.0
- generic-deriving-1.12.1
- integer-logarithms-1.0.2.1
- microlens-0.4.9
- microstache-1.0.1.1
- optparse-applicative-0.14.2.0
- parsec-3.1.13.0
- primitive-0.6.3.0
- rio-0.0.0.0
- scientific-0.3.5.3
- semigroupoids-5.2.2
- statistics-0.14.0.2
- tagged-0.8.5
- tasty-rerun-1.1.10
- th-abstraction-0.2.6.0
- transformers-0.5.5.0
- transformers-compat-0.6.0.6
- typed-process-0.2.1.0
- unliftio-0.2.5.0
- unliftio-core-0.1.1.0
- vector-0.12.0.1
- vector-binary-instances-0.2.4
resolver: lts-6.35
