version: 2
jobs:
  lint:
    docker:
      - image: romanandreg/haskell-tools:latest
    environment:
      - TOOLS_DIR: /root/.local/bin
    steps:
      - checkout
      - run: "make -f make/tools.make lint"

  format:
    docker:
      - image: romanandreg/haskell-tools:latest
    environment:
      - TOOLS_DIR: /root/.local/bin
    steps:
      - checkout
      - run: "make -f make/tools.make format"

  lts-11:
    docker:
      - image: romanandreg/lts-11:latest
    environment:
      - STACK_ARGS: '--resolver lts-11'
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "package.yaml" }}
      - run: "make test"
      - save_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "package.yaml" }}
          paths:
            - /root/.stack
            - .stack-work

workflows:
  version: 2
  main:
    jobs:
      - lint
      - format
      - lts-11
