name: teardown-example
synopsis: example for teardown library
description: see README.md
version: '0.0.0.1'
category: Web
author: Roman Gonzalez
maintainer: open-source@roman-gonzalez.info
copyright: © 2017, 2018 Roman Gonzalez
license: BSD3
github: roman/Haskell-teardown/
extra-source-files:
- README.md
executables:
  teardown-example:
    main: Main.hs
    source-dirs: src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base >=4.8 && <5
    - rio >= 0.0.0.0
    - unliftio >= 0.2.4.0
    - teardown
