name: teardown-example
version: '0.0.0.1'
category: Web
author: Roman Gonzalez
maintainer: romanandreg@gmail.com
copyright: © 2017 Roman Gonzalez
license: BSD3
github: roman/Haskell-teardown/
extra-source-files:
- README.md
executables:
  teardown-example:
    main: Main.hs
    source-dirs: src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base >=4.8 && <5
    - protolude >=0.1 && <0.2
    - teardown
